# Generated by Django 4.1.7 on 2023-03-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Night", "Night"),
                            ("Custom", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Online", "Online"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
