# Generated by Django 4.1.7 on 2023-03-05 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="_class",
            new_name="cclass",
        ),
    ]
