# Generated by Django 4.1.7 on 2023-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
