# Generated by Django 4.1.7 on 2023-03-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("classrooms", "0003_alter_classroom_cclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="cclass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="classes.class",
            ),
        ),
    ]
