# Generated by Django 4.1.7 on 2023-03-15 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("occurrences", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schools", "0001_initial"),
        ("ttests", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="ttests.test",
            ),
        ),
        migrations.AddField(
            model_name="classregistration",
            name="cclass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_registration",
                to="classes.class",
            ),
        ),
        migrations.AddField(
            model_name="classregistration",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "Student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_registration",
                to=settings.AUTH_USER_MODEL,
                to_field="student_id",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="occurrences.occurrence",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "Student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to=settings.AUTH_USER_MODEL,
                to_field="student_id",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
