# Generated by Django 4.1.7 on 2023-03-15 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classregistration",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="registered_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresult",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
