# Generated by Django 4.1.7 on 2023-03-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_full_name_alter_account_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="office",
        ),
        migrations.AddField(
            model_name="account",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="fired_at",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="fired_reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="major",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="middle_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="photo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "School Owner"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                ],
                default="Owner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="student_code",
            field=models.CharField(
                editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="student_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="account",
            name="teacher_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="cpf",
            field=models.IntegerField(
                error_messages={"unique": "This C.P.F field must be unique."},
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email field must be unique."},
                max_length=127,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.BigIntegerField(null=True),
        ),
    ]
