# Generated by Django 4.1.7 on 2023-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_classregistration_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "School Owner"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                    ("ADM", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
