# Generated by Django 4.1.7 on 2023-03-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_account_full_name_remove_account_office_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cpf",
            field=models.BigIntegerField(
                error_messages={"unique": "This C.P.F field must be unique."},
                unique=True,
            ),
        ),
    ]
