# Generated by Django 4.1.7 on 2023-03-12 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_remove_school_account_remove_school_company_name_and_more"),
        ("accounts", "0005_alter_account_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="schools.school",
            ),
        ),
    ]
