# Generated by Django 4.1.7 on 2023-03-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0010_school_is_active"),
        ("accounts", "0006_account_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "School Owner"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="schools.school",
            ),
        ),
    ]
