# Generated by Django 4.1.7 on 2023-03-04 22:11

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0007_school_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("cpf", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Not Informed", "Not Informed"),
                        ],
                        default="Not Informed",
                        max_length=50,
                    ),
                ),
                ("birthdate", models.DateField()),
                ("phone", models.IntegerField()),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "This field must be unique."},
                        max_length=127,
                        unique=True,
                    ),
                ),
                ("photo", models.CharField(max_length=255, null=True)),
                (
                    "register_number",
                    models.CharField(
                        default=students.models.generate_register_number, max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
