# Generated by Django 4.1.7 on 2023-03-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ttests", "0001_initial"),
        ("classes", "0001_initial"),
        ("students", "0002_class_registrations_student_classes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class_Registrations",
            new_name="Class_Registration",
        ),
        migrations.CreateModel(
            name="Test_Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_grade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ttests.test"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="ttests",
            field=models.ManyToManyField(
                related_name="students",
                through="students.Test_Result",
                to="ttests.test",
            ),
        ),
    ]
