# Generated by Django 4.1.7 on 2023-03-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classrooms", "0002_rename__class_classroom_cclass"),
        ("students", "0003_rename_class_registrations_class_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_grade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="classrooms",
            field=models.ManyToManyField(
                related_name="students",
                through="students.Attendance",
                to="classrooms.classroom",
            ),
        ),
    ]
