# Generated by Django 4.1.7 on 2023-03-05 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_attendance_student_classrooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="test_grade",
        ),
        migrations.AddField(
            model_name="attendance",
            name="register_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="showed_up",
            field=models.BooleanField(default=False),
        ),
    ]
