# Generated by Django 4.1.7 on 2023-03-06 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ttests", "0001_initial"),
        ("classes", "0001_initial"),
        ("students", "0005_remove_attendance_test_grade_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class_Registration",
            new_name="ClassRegistration",
        ),
        migrations.RenameModel(
            old_name="Test_Result",
            new_name="TestResult",
        ),
    ]
