# Generated by Django 4.1.7 on 2023-03-06 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_rename_class_registration_classregistration_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="classregistration",
            table="students_class_registration",
        ),
        migrations.AlterModelTable(
            name="testresult",
            table="students_test_result",
        ),
    ]
