# Generated by Django 4.1.7 on 2023-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_alter_classregistration_table_alter_testresult_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="register_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
