# Generated by Django 4.1.7 on 2023-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_alter_attendance_register_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
