# Generated by Django 4.1.7 on 2023-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=127)),
                ("cnpj", models.IntegerField()),
                ("phone_number", models.IntegerField()),
            ],
        ),
    ]
