# Generated by Django 4.1.7 on 2023-03-03 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_rename_schools_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="phone_number",
            new_name="school_phone",
        ),
    ]
