# Generated by Django 4.1.7 on 2023-03-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0005_alter_school_cnpj_alter_school_school_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="cnpj",
            field=models.BigIntegerField(
                error_messages={"unique": "This field must be unique."}, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="company_name",
            field=models.CharField(
                error_messages={"unique": "This field must be unique."},
                max_length=127,
                unique=True,
            ),
        ),
    ]
