# Generated by Django 4.1.7 on 2023-03-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0006_alter_school_cnpj_alter_school_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schools",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
