# Generated by Django 4.1.7 on 2023-03-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classrooms", "0002_rename__class_classroom_cclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1st Quarter", "Fstquarter"),
                            ("2nd Quarter", "Sndquarter"),
                            ("3rd Quarter", "Trdquarter"),
                            ("4th Quarter", "Fthquarter"),
                            ("1st Recovery", "Fstrecovery"),
                            ("2nd Recovery", "Sndrecovery"),
                        ],
                        max_length=50,
                    ),
                ),
                ("test_date", models.DateTimeField()),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=10, max_digits=12),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="classrooms.classroom",
                    ),
                ),
            ],
        ),
    ]
