# Generated by Django 4.1.7 on 2023-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
