# Generated by Django 4.1.7 on 2023-03-15 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Online", "Online"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=6,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "duration_in_weeks",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "The name field must be unique."},
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="theme_courses", to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "The name field must be unique."},
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="level_courses", to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "The name field must be unique."},
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="degree_courses", to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="degrees",
            field=models.ManyToManyField(
                db_table="course_degrees", related_name="course", to="courses.degree"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="levels",
            field=models.ManyToManyField(
                db_table="course_levels", related_name="course", to="courses.level"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="themes",
            field=models.ManyToManyField(
                db_table="course_themes", related_name="course", to="courses.theme"
            ),
        ),
    ]
