# Generated by Django 4.1.7 on 2023-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="courses",
            field=models.ManyToManyField(to="courses.course"),
        ),
        migrations.AlterField(
            model_name="level",
            name="courses",
            field=models.ManyToManyField(to="courses.course"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="courses",
            field=models.ManyToManyField(to="courses.course"),
        ),
    ]
