# Generated by Django 4.1.7 on 2023-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_degree_courses_alter_level_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="degrees",
            field=models.ManyToManyField(related_name="course", to="courses.degree"),
        ),
        migrations.AlterField(
            model_name="course",
            name="levels",
            field=models.ManyToManyField(related_name="course", to="courses.level"),
        ),
        migrations.AlterField(
            model_name="course",
            name="themes",
            field=models.ManyToManyField(related_name="course", to="courses.theme"),
        ),
        migrations.AlterField(
            model_name="degree",
            name="courses",
            field=models.ManyToManyField(
                related_name="degree_courses", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="courses",
            field=models.ManyToManyField(
                related_name="level_courses", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="courses",
            field=models.ManyToManyField(
                related_name="theme_courses", to="courses.course"
            ),
        ),
    ]
